### ISSUE TITLE
Duplicate route keys

### ISSUE THREAD

**Issue by louis-l** [victorgarciaesgi/nuxt-typed-router#1]
Hi there,

Thanks for the package. I have been looking for a way to avoid using magic string for the route names, and this package sounds like the answer for that.

However, when I open the generated route file, there are some duplicate keys in the object.

My pages structure is:

```
settings
   |__ checkout-messages
           |__ _key
                 |__ index.vue
           |__ index.vue
```

and here is the generate route:

```
export const routerPagesNames = {
	...,

	settings: {
		checkoutMessages: {
			index: 'settings-checkout-messages',
      		        index: 'settings-checkout-messages-key'
		},
	},

	...,
}
```

I expect the route JS file should be:

```
settings: {
	checkoutMessages: {
		index: 'settings-checkout-messages',
  		key: {
  			index: 'settings-checkout-messages-key'
  		},
	},
},
```

Note that Im using SPA mode and have the Nuxt generate config `subFolders` set to `false`.

Cheers,

**Comment by victorgarciaesgi** [comment]
Hi @louis-l ! Thanks for the report, I will look at this issue. From the look of it it may comes from the `subFolders` option

**Comment by victorgarciaesgi** [comment]
From your exemple as a workaround you can just have a `_key.vue` file?

**Comment by victorgarciaesgi** [comment]
Okay it's fixed on 1.8!

**Comment by louis-l** [comment]
Thanks for the quick repsonse @victorgarciaesgi 

Updated to the latest version and the issue is fixed.
However, there is another issue with that, now my the generated route file looks like this:

```
export const routerPagesNames = {
	...,

	settings: {
		checkoutMessages: {
			messages: 'settings-checkout-messages',
      		        messagesKey: 'settings-checkout-messages-key'
		},
	},

	...,
}
``` 

Should the `messagesKey` be `key` instead?

**Comment by victorgarciaesgi** [comment]
@louis-l hmm yeah it should be index and `key`, i changed the algorithm , i will look at it this afternoon!

**Comment by victorgarciaesgi** [comment]
@louis-l  I'm not optaining the same result as you with the last version 
```ts
{
 settingCheckoutMessage: 'setting-checkoutMessage',
 settingRoute: 'setting-route',
 settingCheckoutMessageKey: 'setting-checkoutMessage-key',
}

```

**Comment by victorgarciaesgi** [comment]
@louis-l  Okay I found it out. This is normal behaviour for your last result. Look at your `.nuxt/router.js` and look at the generated routes object. This is corresponding to the result. `messages` and `messagesKey` are not children of `checkMessages`.
It will work if you have a `checkMessages.vue` on your `settings` folder

**Comment by louis-l** [comment]
Thanks for looking into this @victorgarciaesgi 

I do have `checkout-messages.vue` under `settings` folder, and my `.nuxt/router.js` looks like this:

```
...
{
  path: "checkout-messages",
  component: _0d561250,
  children: [{
    path: "",
    component: _00bf9cd3,
    name: "settings-checkout-messages"
  }, {
    path: ":key",
    component: _0d3fcbf2,
    name: "settings-checkout-messages-key"
  }]
}
...
```

**Comment by louis-l** [comment]
Here is my `pages` folder structure:

```
...
settings
  |__checkout-messages
    |__ _key  <--  this is a folder named "_key"
      |__index.vue
    |__index.vue
  |__checkout-messages.vue
...
```

Even I rename the `_key/index.vue` to `_key.vue` and move it up (right under the `settings/checkout-messages` folder, the output is still the same.
