### ISSUE TITLE
Nested dynamic routes generates wrong types (nuxt3)

### ISSUE THREAD

**Issue by SimonSimCity** [victorgarciaesgi/nuxt-typed-router#102]
**Describe the bug**
In my project, I discovered that the type definition for `RoutesNamesList` does not contain the right arguments and types for nested dynamic routes. Since it might be a bit hard to explain, imagine the following list of pages:

```
pages/index.vue
pages/track/index.vue
pages/track/[id]/index.vue
pages/track/[id]/[...language].vue
```

After running `nuxi prepare`, the file `.nuxt/typed-router/__routes.ts` contains types like this:

```ts
export type RoutesNamedLocations =
  | { name: 'index' }
  | {
      name: 'track-id-language';
      params: {
        id: (string | number)[];
      };
    }
  | {
      name: 'track-id';
      params: {
        id: string | number;
      };
    }
  | { name: 'track' };
```

**Expected behavior**
The generated types should have the correct typings.

I could see the types looking like:
```ts
export type RoutesNamedLocations =
  | { name: 'index' }
  | {
      name: 'track-id-language';
      params: {
        id: string | number;
        language: string | number | (string | number)[];
      };
    }
  | {
      name: 'track-id';
      params: {
        id: string | number;
      };
    }
  | { name: 'track' };

```
**Screenshots**
-/-

**Environnement infos**

https://stackblitz.com/edit/github-52carx-onevqx?file=layouts%2Fdefault.vue

**Your nuxt.config.ts**

```ts
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  modules: [['nuxt-typed-router', { strict: true }]],
});
```

**Comment by victorgarciaesgi** [comment]
Hi! Indeed that should not be the result, i'll look at it if I have time this week

**Comment by victorgarciaesgi** [comment]
Ok comes from the fact that there isn't a `pages/track/[id].vue`, you can have this as a temp fix while I find the problem

**Comment by SimonSimCity** [comment]
Renaming `pages/track/[id]/index.vue` to `pages/track/[id].vue`, as you proposed creates a definition like ...

```ts
export type RoutesNamedLocations =
  | { name: 'index' }
  | {
      name: 'track-id-language';
      params: {
        id?: string | number;
        language: (string | number)[];
      };
    }
  | { name: 'track' };
```

... which seems weird to me, because `id` is not optional, rather `language`. Also wondering what would happen if you have an even deeper nested dynamic routing 😅

**Comment by victorgarciaesgi** [comment]
Fixed in `3.2.4`

**Comment by SimonSimCity** [comment]
Thanks for the quick fix! 🎉

Interestingly, the router also accepts a string or number as argument for `language`, but since a link to `/track/50/en` would result in an array for the parameter `language`, this seems to be something we can fix by the type only allowing an array.

**Comment by victorgarciaesgi** [comment]
> Renaming `pages/track/[id]/index.vue` to `pages/track/[id].vue`, as you proposed creates a definition like ...
> 
> ```ts
> export type RoutesNamedLocations =
>   | { name: 'index' }
>   | {
>       name: 'track-id-language';
>       params: {
>         id?: string | number;
>         language: (string | number)[];
>       };
>     }
>   | { name: 'track' };
> ```
> 
> ... which seems weird to me, because `id` is not optional, rather `language`. Also wondering what would happen if you have an even deeper nested dynamic routing 😅

For this it was a decision choice, because with vue-router you can navigate between children routes without the need to re-provide the main parent parameter. So that's why it's optional :/ 

> Thanks for the quick fix! 🎉
> 
> Interestingly, the router also accepts a string or number as argument for `language`, but since a link to `/track/50/en` would result in an array for the parameter `language`, this seems to be something we can fix by the type only allowing an array.


I don't understand this part, do you have an exemple? :) 
You can do `router.push({name: 'track-id-languages', params: {languages: [50, 'en'], id: 1}})`

**Comment by SimonSimCity** [comment]
> For this it was a decision choice, because with vue-router you can navigate between children routes without the need to re-provide the main parent parameter. So that's why it's optional :/

But shouldn't the parameter `language` be optional and not `id` ..? What route would actually be generated if I'd just pass the language?

I tried to generate a route for `{ name: 'track-id-language', params: { language: [50] } }` and it failed by a 500-error `Missing required param "id"`, even though it would've been valid as of the generated types.

> I don't understand this part, do you have an exemple? :)
> You can do `router.push({name: 'track-id-languages', params: {languages: [50, 'en'], id: 1}})`

Yes, but a valid route would also be generated when I do `router.push({name: 'track-id-languages', params: {languages: 'en', id: 1}})`, and the parameter `language` would be a string. But when opening the generated url (`/track/1/en`), it is an array. To me this means, the only way the parameter `language` would be a string is when I call the router with a string as parameter. That said, if you never pass a string but only arrays (which is the only allowed option by the parameter) it will always be an array.
