### ISSUE TITLE
stackblitz demo not working

### ISSUE THREAD

**Issue by VladBrok37** [victorgarciaesgi/nuxt-typed-router#107]
Steps to reproduce:

1. Go to https://stackblitz.com/edit/github-7e4xvw?file=store%2FtestRouter.ts
2. Wait until all types are generated
3. Go to file pages/user/[id]/index.vue
Autocompletes in nuxt-link not working (Ctrl + Space shows "no suggestion")

tested on latest chrome and firefox, operating system - lubuntu linux

**Comment by VladBrok37** [comment]
Here is a video demo.
Everything works fine only in the .ts file

https://github.com/victorgarciaesgi/nuxt-typed-router/assets/116383318/aaf4fd09-ae7b-4167-99c4-948d97c01ac5

**Comment by victorgarciaesgi** [comment]
It's explained in the comment on the typescript file, StackBlitz has no support for Vue langage server yet

> Stackblitz does not support Typescript on `.vue` files yet,
> so to test `<NuxtLink/>` you have to clone and open VSCode localy.
