### ISSUE TITLE
Add Object-syntax support for `to` param

### ISSUE THREAD

**Issue by mrleblanc101** [victorgarciaesgi/nuxt-typed-router#117]
Would it be possible to also support the Object-syntax for the NuxtLink `to` parameter ?
Currently, you only support String.

**Comment by victorgarciaesgi** [comment]
https://nuxt-typed-router.vercel.app/usage/nuxtlink

**Comment by mrleblanc101** [comment]
Ohh I'm sorry, I didn't notice there was a website with more info in the README.
