### ISSUE TITLE
Parameter type generated wrongfully when using a directory containing a parameter

### ISSUE THREAD

**Issue by just-maik** [victorgarciaesgi/nuxt-typed-router#118]
**Describe the bug**
When using a directory containing a parameter and another parameter on a deeper level (as shown in the screenshot) typed router generates:
```
<{
     lang: string[]
}>
```
ignoring the second parameter

**Expected behavior**
```
<{
     lang: string
     slug: string
}>
```

**Screenshots**
![image](https://github.com/victorgarciaesgi/nuxt-typed-router/assets/16877165/c24f7b78-1d6b-4fea-be8c-ec13b21550e5)
![image](https://github.com/victorgarciaesgi/nuxt-typed-router/assets/16877165/20ca740e-47a9-411e-8159-8d01d143f9ab)

**Environnement infos**

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools, telemetry, modules, runtimeConfig, graphql-client, security, app, typescript
- Runtime Modules:  @vueuse/nuxt@9.13.0, @nuxtjs/device@3.1.1, nuxt-security@0.10.2, nuxt-graphql-client@0.2.30, nuxt-typed-router@2.3.5, nuxt-icon@0.2.11, nuxt-simple-sitemap@2.7.0, @dargmuesli/nuxt-cookie-control@5.10.4, nuxt-vitest@0.8.7, @nuxtjs/tailwindcss@6.8.0
- Build Modules:    -

**Your `pages` folder structure**

pages
├── [lang]
│   ├── index.vue
│   ├── posts
│   │   └── [slug].vue
│   ├── products
│   │   ├── [slug].vue
│   │   └── index.vue
│   └── reseller.vue
└── index.vue

**Comment by victorgarciaesgi** [comment]
Hello! Can't reproduce on my side, can you make a reproduction here please? 
https://stackblitz.com/edit/github-7e4xvw?file=package.json,store%2FtestRouter.ts

**Comment by just-maik** [comment]
https://stackblitz.com/edit/github-7e4xvw-wtn1i3?file=pages%2F%5Blanguage%5D%2Fuser%2F%5Bid%5D%2Fposts.vue

I hope this works, otherwise I can provide a reproduction repo

**Comment by victorgarciaesgi** [comment]
@just-maik In your repro I have the correct types :/ 
<img width="434" alt="image" src="https://github.com/victorgarciaesgi/nuxt-typed-router/assets/15092120/555f0bb7-6f78-43ee-a90b-69ce45ddeeba">


The intellisense doesn't work so test on the .ts file :)

**Comment by victorgarciaesgi** [comment]
There's maybe a module that interfere with it, do you use i18n?

**Comment by victorgarciaesgi** [comment]
Just saw `nuxt-typed-router@2.3.5`, install the latest version `3.3.1`

**Comment by just-maik** [comment]
Well that fixed my issue...
I was so sure I manually updated to the latest version, but my package.json kept 2.3.5 😄 

Thanks for the fast response!
