### ISSUE TITLE
Bug: Incompatibility with turborepo caching system

### ISSUE THREAD

**Issue by malkhuzayyim** [victorgarciaesgi/nuxt-typed-router#131]
Hi Victor. Awesome plugin you got here, loving how useful it is.

**Describe the bug**
Turbo repo relies on input/output hashes of files to properly cache tasks

I was trying to cache my `nuxt prepare` task but it was always missing the cache, upon further investigation I realized it's due to how nuxt-typed-router generates it's type signatures.

You append a random suffix to type signature names for some reason (might be a good one, idk), to route validations type signatures.  Which changes everytime the nuxt prepare task runs.

**Expected behavior**

The output should be always consistent (reliably the same) if the inputs did not change.

**Screenshots**

![image](https://github.com/victorgarciaesgi/nuxt-typed-router/assets/12685327/3ac94690-d5dc-4ba9-bf9d-c4dc9f1eaec8)

**Environnement infos**

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.18.2
- Nuxt Version:     3.7.4
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  pnpm@8.10.5
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

**Your `pages` folder structure**
N/A

**Your nuxt.config.ts**
N/A

**Current Workaround**

To ignore the file using `"!__paths.d.ts"` in the turbo outputs of `nuxt:prepare`

**Comment by victorgarciaesgi** [comment]
Hi @malkhuzayyim thanks 😇

Ok weird at my company we use turbo too but never noticed this, but that could be a great thing to improve. 
It's generated IDs because there is a lot a variables to create for each route, but I think it could be cached with a random seed for each route, i'll look at this monday

**Comment by victorgarciaesgi** [comment]
Fixed in `v3.5.0`

**Comment by victorgarciaesgi** [comment]
@malkhuzayyim Did you see any improvement one your side? 
On our monorepo with the update I didn't see any improvements :(

Before: 
<img width="257" alt="image" src="https://github.com/victorgarciaesgi/nuxt-typed-router/assets/15092120/ad5ff4a5-1b9b-4278-ba37-c8e79fbcc570">

After: 
<img width="258" alt="image" src="https://github.com/victorgarciaesgi/nuxt-typed-router/assets/15092120/bcdc4507-0300-4057-84a1-f541ad63edea">
