### ISSUE TITLE
"Cannot start nuxt:  Nuxt module should be a function: nuxt-typed-router" on Nuxt 3.9.0

### ISSUE THREAD

**Issue by wladyslaw-malejew** [victorgarciaesgi/nuxt-typed-router#134]
**Describe the bug**
When trying to "yarn dev" on Nuxt 3.9.0 -- having this error

**Expected behavior**
Dev server starts successfully

**Reproduction**
https://stackblitz.com/edit/github-7e4xvw-s3cqyv

**Comment by wladyslaw-malejew** [comment]
adding "prettier" solves the issue:

"yarn add prettier"

**Comment by victorgarciaesgi** [comment]
Mmh I think there might be a problem on my side too
