### ISSUE TITLE
Specific use case that generates wrong routes

### ISSUE THREAD

**Issue by iamandrewluca** [victorgarciaesgi/nuxt-typed-router#28]
https://github.com/iamandrewluca/issue-nuxt-typed-router

ps: I may take some time later to investigate this issue, if no one else will take it.

![image](https://user-images.githubusercontent.com/1881266/134345102-2f50523b-d427-4209-a0fa-6e5cbd667913.png)

**Comment by victorgarciaesgi** [comment]
Oh yeah that seems to be an edge case, I will look into this

**Comment by victorgarciaesgi** [comment]
@iamandrewluca Can you link me the repo or make a codesandbox with it? :)

**Comment by iamandrewluca** [comment]
@victorgarciaesgi sure! https://github.com/iamandrewluca/issue-nuxt-typed-router

**Comment by victorgarciaesgi** [comment]
@iamandrewluca in the meantime, you can add a `parent.vue` at the root level to fix the generated output. I'm working on a fix on this!

**Comment by victorgarciaesgi** [comment]
If you want to know the origin of the bug, it comes from what nuxt generated routes chunk send to me.

```js
[                                                                      17:03:55
  {
    name: 'parent',
    path: '/parent',
    component: '/Users/victorgarcia/Desktop/Projects/nuxt-typed-router/test/pages/parent/index.vue',
    chunkName: 'pages/parent/index'
  },
  {
    path: '/parent/child-one',
    component: '/Users/victorgarcia/Desktop/Projects/nuxt-typed-router/test/pages/parent/child-one.vue',
    chunkName: 'pages/parent/child-one',
    children: [
      [Object],
      [Object],
      [Object]
    ]
  },
  {
    path: '/parent/child-two',
    component: '/Users/victorgarcia/Desktop/Projects/nuxt-typed-router/test/pages/parent/child-two.vue',
    chunkName: 'pages/parent/child-two',
    children: [
      [Object],
      [Object]
    ]
  },
  {
    name: 'index',
    path: '/',
    component: '/Users/victorgarcia/Desktop/Projects/nuxt-typed-router/test/pages/index.vue',
    chunkName: 'pages/index'
  }
]
```

See, `child-one` and `child-two` are not in the `children` of `parent`. So i juste have to check the siblings for similar origins!

**Comment by iamandrewluca** [comment]
So we need to join routes that begin with same `path` segment. Cool

**Comment by victorgarciaesgi** [comment]
@iamandrewluca Should be fixed in `0.2.21` !

**Comment by victorgarciaesgi** [comment]
`0.2.22`* made another small fix on key names

**Comment by iamandrewluca** [comment]
@victorgarciaesgi Thanks a lot!

**Comment by victorgarciaesgi** [comment]
Aw f**k yeah i need to put up some tests but i lack time sorry 😩

**Comment by iamandrewluca** [comment]
I'll close this because it seems it become outdated
