### ISSUE TITLE
Some route params are not generated

### ISSUE THREAD

**Issue by zwj-cheer** [victorgarciaesgi/nuxt-typed-router#41]
In the generatedxxxxx route, path parameter hash is not generated, also I don't understand why is the type of parameter chainIdoptional?

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/71361115/185359598-59ea2d2e-95bb-482e-b0d4-2e5151ce7d1a.png">

**Comment by victorgarciaesgi** [comment]
chainId is optional because when a parameter is required and you are navigating between its children routes, precising the param is not mandatory and will resolve itself

**Comment by victorgarciaesgi** [comment]
It depends from where you are navigating

**Comment by victorgarciaesgi** [comment]
And do not understand the `hash` problem tho

**Comment by zwj-cheer** [comment]
@victorgarciaesgi 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/71361115/188127673-60b339e3-4515-4a36-8549-f62fc9d9f177.png">

**Comment by zwj-cheer** [comment]
Hash is not generated

**Comment by victorgarciaesgi** [comment]
@zwj-cheer Can you provide me a simple reproduction of your `pages` folder (with empty components)?
Also are you using nuxt 2 or 3?

**Comment by zwj-cheer** [comment]
@victorgarciaesgi HI i am currently using ```nuxt 3.0.0-rc.8``` , reproduction repo:
https://github.com/zwj-cheer/nuxt-starter/blob/533b497db38e9de52b0b809d3c87ab6b86560232/generated/typed-router/typed-router.d.ts#L32-L34

**Comment by victorgarciaesgi** [comment]
Sorry for a so late response, I don't know when I fixed it but it works with latest version! :D
