### ISSUE TITLE
Nuxt CLI stuck after upgrading to rc6 or above

### ISSUE THREAD

**Issue by kstraszewski** [victorgarciaesgi/nuxt-typed-router#42]
Hi, after upgrading nuxt to rc6 or above (curretly testing it on rc8) my cli stuck  when I use TypedRouter:

```
  buildModules: [
    '@pinia/nuxt',
    '@vueuse/nuxt',
    TypedRouter,
  ]
```
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/10195995/186654482-7190c124-10a3-4049-a0a8-a906aaa69559.png">

When I remove it:
```
  buildModules: [
    '@pinia/nuxt',
    '@vueuse/nuxt',
  ]
```
Everything works fine

**Comment by victorgarciaesgi** [comment]
Hi! I will look at it if I have time :)

**Comment by kstraszewski** [comment]
I found what is responsible for that. It is a ["c12"](https://www.npmjs.com/package/c12) library which is implemented by @nuxt/kit. When I install version 0.2.8 everything works great. But when I install version 0.2.9 this error occurred. CLI just stuck :(

**Comment by kstraszewski** [comment]
Today "c12" 0.2.10 landed but unfortunately, still the same result, installing c12 0.2.10 or 0.2.9 crashes cli :(

I've found out that updating to rc8 forces npm to install c12 latest version even when I have c12 0.2.8 in dependencies :(

**Comment by victorgarciaesgi** [comment]
I have trouble to run tests with nuxt-rc.10 since I upgraded too

**Comment by victorgarciaesgi** [comment]
Should work with `1.2.0` :D 
Nuxt updated imports from `nuxt3` to `nuxt`

**Comment by kstraszewski** [comment]
Unfortunately still does not work :(

Here is a reproduction: 
https://stackblitz.com/edit/github-w6cj1g-avaha4?file=nuxt.config.ts

**Comment by victorgarciaesgi** [comment]
It's realy weird, in the local playground it works well 
![image](https://user-images.githubusercontent.com/15092120/188630473-2e4dc8ae-0195-4c7e-9fa5-8657bf596edd.png)

But when I test it on an external project Nuxt in stuck with no log whatsoever. I have exactly the same structure as their [Module starter](https://github.com/nuxt/starter/blob/module/src/module.ts)

**Comment by victorgarciaesgi** [comment]
Wow I found it 😂 

Just replace 
```ts
buildModules: [
    '@pinia/nuxt',
    '@vueuse/nuxt',
   'nuxt-typed-router',
  ]

**Comment by victorgarciaesgi** [comment]
I will modify the Readme

**Comment by kstraszewski** [comment]
ok it is working but on rc9 i have an error:
```
WARN  Module nuxt-typed-router is disabled due to incompatibility issues:                                                                                        14:09:57
 - [nuxt] Nuxt version `^3.0.0` is required but currently using `3.0.0-rc.9`
```

Here is info about that error: https://github.com/nuxt/framework/releases/tag/v3.0.0-rc.9

Here is how to fix it: https://github.com/ymmooot/nuxt-jsonld/pull/952/files

**Comment by victorgarciaesgi** [comment]
Available in `1.2.2`

**Comment by kstraszewski** [comment]
ok, everything works great! Thanks a lot!

**Comment by victorgarciaesgi** [comment]
🎉
