### ISSUE TITLE
Question: Is it possible to specify other than the pages directory?

### ISSUE THREAD

**Issue by shamscorner** [victorgarciaesgi/nuxt-typed-router#46]
I have a Nuxt 3 project. There I am using a modular architecture pattern so I don't have anything inside the `pages/` directory. It is basically empty with a `.gitkeep` file.

My pages are inside a dedicated folder `features/` with modules like below:

- `features/common/pages/*.vue`
- `features/users/pages/*.vue`
- and so on...

So maybe something like a glob pattern that I can provide somewhere on the configuration like `features/**/*.vue`.

Can I do that?

**Comment by victorgarciaesgi** [comment]
Hi!

Sorry to respond so late.
Unfortunately I rely on Nuxt routing system to generate types, I will check if it's possible in Nuxt.

What I know is that my module can handle pages specified in the `extendRoutes` property
