### ISSUE TITLE
The requested module '/_nuxt/.nuxt/typed-router/__routes.ts' does not provide an export named 'TypedRouteList'

### ISSUE THREAD

**Issue by AnoRebel** [victorgarciaesgi/nuxt-typed-router#56]
In the latest 2.0.0 release, I get the above error.
Even in the stackblitz example on the [playground page](https://nuxt-typed-router.vercel.app/playground), the same thing happens.

**Comment by victorgarciaesgi** [comment]
Hi! Did you ran `npm run dev` or `npm run prepare` before? It's needed to generate `.nuxt` files

**Comment by victorgarciaesgi** [comment]
But looking at your repo made me think I can improve support for catchAll routes like `[...slug].vue`

**Comment by victorgarciaesgi** [comment]
@AnoRebel You're right there were a messed up bug on exports in the generated file. Fixed in `2.0.1`

**Comment by AnoRebel** [comment]
Ohw, okay, cool..
Is the 2.0.1 out ?

**Comment by victorgarciaesgi** [comment]
Yep!
Playground updated too

**Comment by AnoRebel** [comment]
Awesome, thanks for the quick fix 👍🏽 !

**Comment by victorgarciaesgi** [comment]
No problem! Thanks for the issue report 😁
