### ISSUE TITLE
combination of nuxt-typed-router and vuestic breaks the auto-import / component resolution of Volar

### ISSUE THREAD

**Issue by thunfisch987** [victorgarciaesgi/nuxt-typed-router#71]
Hi,
when using nuxt-typed-router and vuestic (@vuestic/nuxt) together the auto-imports / component resolution of Volar breaks.
It only works when implicitly importing every component.
_This is only a problem with Volar_, nuxt dev and so on still works.
It still works when only using one of them, but breaks when using both.
How can i get more information about why it breaks?
_Should i rather only ask in the repository of Volar?_

**Comment by thunfisch987** [comment]
### It works when reloading VSCode but as soon as you change something in the file or go to another file it breaks:
![image](https://user-images.githubusercontent.com/43795814/219022816-43fd3979-9ae2-498d-9eaf-33ffe1e7537f.png)
![image](https://user-images.githubusercontent.com/43795814/219022843-63dde140-0d41-4fa3-ba1b-0c4d44a4ea3b.png)
### changing something:
![image](https://user-images.githubusercontent.com/43795814/219022869-abfbb535-c34c-48fc-b216-34d07b4ce4c0.png)
![image](https://user-images.githubusercontent.com/43795814/219023207-00de9fc5-3eaf-4f0b-9171-0e23fb822fb2.png)
### implicitly importing the component
![image](https://user-images.githubusercontent.com/43795814/219022894-71a2400b-3911-4784-bd39-71fef3047004.png)

**Comment by thunfisch987** [comment]
#70 probably/maybe fixes this, i'm gonna test when i'm home

**Comment by thunfisch987** [comment]
It's fixed! Thanks @mahdiboomeri !

**Comment by thunfisch987** [comment]
tried the 3.0.0 version, it's back again.
might be because of the Route path autocomplete

**Comment by thunfisch987** [comment]
dev server runs fine, but the types aren't working

**Comment by victorgarciaesgi** [comment]
Arrg this one is so frustrating. I had to revert to `@vue/runtime-core` because `vue-router` is using it too and breaking all other typings with it. I will see how to correct this nicely

**Comment by victorgarciaesgi** [comment]
You can try `v3.0.1`, reverted it to 'vue'

**Comment by thunfisch987** [comment]
That seems to have worked!
