### ISSUE TITLE
Some of dynamic routes are skipped in routesNames

### ISSUE THREAD

**Issue by Jassmin586** [victorgarciaesgi/nuxt-typed-router#75]
I've upgrade `nuxt-typed-router` from `2.2.1` version to `3.0.1`.

In project I've structure with `[slug].vue` or `categories/[slug].vue`.

Before upgrade - `routesNames.categoriesSlug`  exists, after upgrade to `3.0.1` this key disappeared.

"nuxt-typed-router": "^3.0.1"
"@nuxtjs/i18n": "^8.0.0-beta.6"

![image](https://user-images.githubusercontent.com/19594765/221556190-c1d4502e-b248-441c-8e8b-de716eca2486.png)
![image](https://user-images.githubusercontent.com/19594765/221556278-d939298c-6cb4-4b69-a900-a3c4b5c620ff.png)
![image](https://user-images.githubusercontent.com/19594765/221556319-be32faa5-ef24-4574-93a4-e2c7e8823240.png)

I think that `[slug].vue` on root may be affect on others nested `*/[slug].vue` routes. When I change `[slug].vue` on root to `[page].vue` - others keys for `*/[slug].vue` appear.

![image](https://user-images.githubusercontent.com/19594765/221557789-0af29fd1-5cdd-4544-a384-9a918eeee8f7.png)

**Comment by victorgarciaesgi** [comment]
Hi thanks for the report! I will look at this it may have been filtered out

**Comment by victorgarciaesgi** [comment]
Okay found it, it was due to the removal of prefixed routes like `/en/xxx`. It would recognize `/category/:slug` as a prefixed route for `/:slug`.
I've improved the matcher to take only the registered locales into account for the filter

**Comment by victorgarciaesgi** [comment]
Fixed in `v3.0.2`
