### ISSUE TITLE
Bug with i18n `prefix_except_default` strategy

### ISSUE THREAD

**Issue by victorgarciaesgi** [victorgarciaesgi/nuxt-typed-router#76]
This works fine for `prefix_and_default`, thanks ;) How about i18n `prefix_except_default` strategy?
In this option `routesNames` keys have name with language prefix.

![2023-02-27_11-09](https://user-images.githubusercontent.com/19594765/221535556-5f02daa0-fb60-4995-8dee-acd36600d400.png)

"nuxt-typed-router": "^3.0.1"
"@nuxtjs/i18n": "^8.0.0-beta.6"

_Originally posted by @Jassmin586 in https://github.com/victorgarciaesgi/nuxt-typed-router/issues/48#issuecomment-1446054469_

**Comment by Jassmin586** [comment]
Thank you very much :heart: You're awesome!
