### ISSUE TITLE
External URL Support in strict mode?

### ISSUE THREAD

**Issue by chrisspiegl** [victorgarciaesgi/nuxt-typed-router#80]
Hello there,

I really like using the typed router to make sure I don't make any mistakes.

With Nuxt 3, the NuxtLink component supports the use of either `href` or `to` to link to external resources (like a url starting with `https://test.com`.

However, the Nuxt Typed Router complains either way (when using `href` or `to`)… that kinda makes sense since raw paths are not supposed to be sued… but would it be possible to support external links?

Or am I missing a config / parameter which would give me the support I need?

**Comment by victorgarciaesgi** [comment]
Hi @chrisspiegl ! If I understand correctly you want to be able to use `<NuxtLink to="google.com" external/>` in strict mode without being able to do `<NuxtLink to='/login'/>` ?

You aren't missing any config I think it could be an improvement (if it's feasible) 😅

**Comment by chrisspiegl** [comment]
Pretty much, to clarify a bit more:

Correct:

- <NuxtLink to="https://google.com" external />
- <NuxtLink to="/about" external /> 
- <NuxtLink :to="{ name: 'login'}" />

Should show error:
- <NuxtLink to="https://google.com" />
- <NuxtLink to="/login" />

The idea would be that only external links are allowed to use the to as a string. All others are supposed to be forced to use the `object` structure.

But there are rare cases where even a `/about` link or maybe `/blog` would make senses as an `external` link (when using a sub directory to setup a blog engine for example.

Not sure if all this would even be possible, but wanted to suggest it anyways 🌸.

**Comment by victorgarciaesgi** [comment]
Bad news for now, I managed to do it, it keeps type checking the path, but we loose the auto-suggestion. I will open a bug to Volar to see how we can override this

**Comment by chrisspiegl** [comment]
That's great and sad at the same time. Auto suggestion are pretty important 👍. I hope you can get something working with Volar maybe.

**Comment by victorgarciaesgi** [comment]
Yep :/ 
At least i think it's related to Volar because the autosuggestion don't work on vue templates and render functions, but works with raw typescript

**Comment by victorgarciaesgi** [comment]
@chrisspiegl Looks like I have good news 
![image](https://user-images.githubusercontent.com/15092120/229064837-77d8bda4-dd9d-48ae-99b5-28b1dd614348.png)

**Comment by victorgarciaesgi** [comment]
I was just VScode being weird 😂

**Comment by chrisspiegl** [comment]
That's great news. I'm looking forward to testing it when a release is ready.

**Comment by victorgarciaesgi** [comment]
You can try it on `3.1.0-beta.0`

**Comment by chrisspiegl** [comment]
I have tried it out but it does not seem to work as expected.
It seems to allow strings in the `to` field now when not in strict and having the `external` parameter.
But in strict it still gave me an error about strings not being allowed in the `to` field?

In non strict mode: I entered one valid path and it validated it but autocomplete only showed me the file structure, not the valid paths which are actually in the router.

In strict mode: it just shows that strings are not allowed in the `to` field.

**Comment by victorgarciaesgi** [comment]
Ok I see, seems like the problem I had when testing too. What version of Typescript are you on?

**Comment by victorgarciaesgi** [comment]
Looking at the problem for strict mode

**Comment by chrisspiegl** [comment]
I have `"typescript": "^5.0.2"` installed in this project.

**Comment by victorgarciaesgi** [comment]
When I had the problem with vscode showing the file structure it was with ts 5.0.2 too, but after upgrading to 5.0.3 the problem was gone. (Screen from a demo project to test it)
![image](https://user-images.githubusercontent.com/15092120/229573185-79cae2dd-dfc0-4081-8c3e-398d6b6a5581.png)

**Comment by victorgarciaesgi** [comment]
@chrisspiegl just released `v3.1.0-beta.1` with strict mode fix, also added support for `navigateTo`!

**Comment by chrisspiegl** [comment]
yes, I just tested it on the links I have in my project and it appears to be working correctly with `3.1.0-beta.1` and `typescript 5.0.3` 👍 .

This is phenomenal work. Thank you.

**Comment by sawa-ko** [comment]
When i try to add a string url to `to` option, i got this error:

![image](https://user-images.githubusercontent.com/56084970/229890313-6186958f-cb61-48f3-9c7e-a0a70fdfdd1c.png)

Version: `"nuxt-typed-router": "3.0.1-beta.1"`
TypeScript: `5.0.2 (takeover)`

**Comment by victorgarciaesgi** [comment]
@sawa-ko expexted behaviour. `string` is not a type safe path.
Either type your url with `as const` to have the real value, or disable path type checking with the `pathCheck: false`.

I will export a utility type to override this behaviour and to replace `as const`

**Comment by victorgarciaesgi** [comment]
@sawa-ko Merged in 3.10 with the type `TypedRouteLocation` to do type assertion

**Comment by sawa-ko** [comment]
@victorgarciaesgi now i got this error:
```
Error:  [unhandledRejection] ENOENT: no such file or directory, open '/home/runner/work/dashboard/dashboard/.nuxt/components.d.ts'
```

**Comment by chrisspiegl** [comment]
@sawa-ko I also have seen this pop up, but didn't think it is related to typed router. But maybe it is?

**Comment by sawa-ko** [comment]
@chrisspiegl Well, that workflow was done by renovate because it created a branch to update that dependency and that happened. So it would be the library's fault since the last update removes/modifies that file.

**Comment by victorgarciaesgi** [comment]
Did you run `nuxt prepare` before?

**Comment by victorgarciaesgi** [comment]
Disable it in the meantime with `experimentalRemoveNuxtDefs: false`

**Comment by sawa-ko** [comment]
@victorgarciaesgi with the version 3.1.1 i get this error in the console: `Error:  [unhandledRejection] ENOENT: no such file or directory, open '/home/runner/work/dashboard/dashboard/.nuxt/types/imports.d.ts'`

**Comment by victorgarciaesgi** [comment]
Oups yeah forgot one, fixed in new release. Is it only happening in CI?

**Comment by sawa-ko** [comment]
No, since in Vercel i was also getting the error.

**Comment by sawa-ko** [comment]
Now all works perfect! :shipit:
