### ISSUE TITLE
Query should support objects?

### ISSUE THREAD

**Issue by chrisspiegl** [victorgarciaesgi/nuxt-typed-router#82]
Hi there, I just wanted to assign an object to the `query` part of a `:to={}` statement.

It says I am not allowed to assign an `{}` or `{ redirect: '/dashboard'}`.

<img width="854" alt="Capture 2023-04-04 at 11 03 51" src="https://user-images.githubusercontent.com/1096384/229676568-e0957286-f742-429c-98c9-9c0b22f6afec.png">

It seems to me that the router supports objects and spreads them into the query of the URL so maybe this can be supported here as well?

**Comment by victorgarciaesgi** [comment]
Weird I didn't touched the query types, I will look at this

**Comment by victorgarciaesgi** [comment]
No error on my side, even with strict mode, I do not modify the `query` option so it's the `vue-router` one.
Can you show me what you have if you `ctrl+click` on query?

**Comment by chrisspiegl** [comment]
That's interesting. Then it may not be related to this, but maybe you can help finding the place where I may post this then.

These are a few tests to see what works and what does not.

The `ctrl+click` didn't give me anything besides the `right click` menu (I am on macos). I also tried `cmd+click` and `option+click` but non gave me any added information.

Interestingly, this is with the `nuxt-typed-router` disabled in the `nuxt.config.ts`:

<img width="866" alt="Capture 2023-04-05 at 09 01 46" src="https://user-images.githubusercontent.com/1096384/229954958-2b833050-84b3-4a60-9813-45b0d2c57528.png">

<img width="771" alt="Capture 2023-04-05 at 09 01 57" src="https://user-images.githubusercontent.com/1096384/229954954-1a5b775c-62d3-4103-86e7-eec5227fe353.png">
