### ISSUE TITLE
`localePath` returns `any` type

### ISSUE THREAD

**Issue by szulcus** [victorgarciaesgi/nuxt-typed-router#83]
Is this correct? Why not `string`?
![image](https://user-images.githubusercontent.com/48328739/230624850-398a8443-8352-40f5-8c2c-1320cb46304d.png)
![image](https://user-images.githubusercontent.com/48328739/230625041-ae5b1e8f-3ff7-4ebb-8c72-01849f8f2d55.png)

**Comment by victorgarciaesgi** [comment]
Seems like a Typescript problem. `TypedToLocalePath` is a combination of 2 function overloads, each one with different generics sont I don't think `ReturnType` can resolve it.
If that solves your problem I can export the `TypedToLocalePath` from `@typed-router`

**Comment by szulcus** [comment]
@victorgarciaesgi Yes you can export it. Thanks!

**Comment by szulcus** [comment]
@victorgarciaesgi Sorry I'm writing now. I missed it 😅. Using `ReturnType<TypedToLocalePath>` also gives me the type `any`. I suspect it's because the `to.name` argument is not defined. How can I do it?
