### ISSUE TITLE
Not all routes in generated type "RoutesNamesList"

### ISSUE THREAD

**Issue by SimonSimCity** [victorgarciaesgi/nuxt-typed-router#87]
In my project, I discovered that the type definition for `RoutesNamesList` only contains the first 3 of my pages, where the last one is `index`. Folders seem to be skipped as well as the files below `index`.

nuxt-typed-router: `3.1.4`
nuxt: `3.4.2`

Any idea of how I can get more information during `nuxt prepare`? I guess its some problem in there ...

**Comment by SimonSimCity** [comment]
Seems the reason for this in my case is the fact that I have an `index.vue` file inside the `pages` folder. After removing it, all routes are generated as expected.

Here's the output of `ls pages/*/*` which shows you the pages I have in my project:
```
pages/audiobooks.vue            pages/index.vue                 pages/not-found.vue             pages/playlist/private/[id].vue
pages/browse.vue                pages/messages.vue              pages/playlist/curated/[id].vue pages/search.vue
```

With this setup, I get the following type:
```ts
export type RoutesNamedLocations = { name: 'audiobooks' } | { name: 'browse' } | { name: 'index' };
```

After removing `pages/index.vue` the following type is generated:
```ts
export type RoutesNamedLocations =
  | { name: 'audiobooks' }
  | { name: 'browse' }
  | { name: 'messages' }
  | { name: 'not-found' }
  | {
      name: 'playlist-curated-id';
      params: {
        id: string | number;
      };
    }
  | {
      name: 'playlist-private-id';
      params: {
        id: string | number;
      };
    }
  | { name: 'search' };
```

Which is as I need it 😅

**Comment by victorgarciaesgi** [comment]
Hi! Thanks for the details. Indeed that's a weird ouput
As for implementation details, I'm mapping over what Nuxt generates, so everything that comes out is only what Nuxt outputs, i will try to reproduce it thanks for the repo! :D

**Comment by victorgarciaesgi** [comment]
Maybe a problem with `@nuxtjs/i18n` i'll investigate

**Comment by victorgarciaesgi** [comment]
Found the cause, will publish a patch shortly

**Comment by cannap** [comment]
i alway get this output 

export type RoutesNamesList =
  | 'dashboard___en'
  | 'index___en'
  | 'me___en'
  | 'me-settings___en'
  | 'signin___en'
export type WithoutBracket<T extends string> = T extends `:${string}`
  ? never
  : T
![image](https://user-images.githubusercontent.com/1394151/233790626-7d6f6ca4-4dda-446d-a1e4-1f78f5056530.png)

```js
 i18n: {
    // strategy: 'prefix_except_default',
    lazy: true,
    defaultLocale: 'en',
    langDir: 'locales',
    locales: [
      { code: 'en', file: 'en.json', iso: 'en-US', name: 'English' },
      { code: 'de', file: 'de.json', iso: 'de-DE', name: 'German' }
    ]
  
  },```
  
"nuxt-typed-router": "3.1.4",
"@nuxtjs/i18n": "8.0.0-beta.11",

**Comment by victorgarciaesgi** [comment]
You can try on 3.1.5

**Comment by SimonSimCity** [comment]
Well, that doesn't really fix it in my particular case. I have the some settings set for `i18n` just not in my example 😇

When setting the property `strategy` it works, but when not defining it, it doesn't do as expected.

I've updated the repo accordingly - the changes chan be found in this commit: https://github.com/SimonSimCity/nuxt-typed-routes-bug/commit/1fe1570874fb6715890f9b1c0b77dd5812d09279

**Comment by SimonSimCity** [comment]
This isn't so relevant for me, as I need to set `strategy` to `no_prefix`, but still would be nice for other people to fully support these other options as well or add a note about it 😏

**Comment by victorgarciaesgi** [comment]
Weird! It's supposed to support all strategies, but as Nuxt made breaking changes in 3.4 maybe the nuxjs/i18n plugin isn't updated yet to support it either

**Comment by victorgarciaesgi** [comment]
Okay the module changes it's default strategy, now it's `prefix_execpt_default`.
Publish the changes on a minor version because there may be breaking changes
`3.2.0-beta.0` if you can try it

**Comment by SimonSimCity** [comment]
Yepp, works 🎉
