### ISSUE TITLE
Use module in `definePageMeta().validate`

### ISSUE THREAD

**Issue by szulcus** [victorgarciaesgi/nuxt-typed-router#91]
Can I write it clearly?
```ts
import { TypedRouteFromName } from '@typed-router';
definePageMeta({
	validate: (currentRoute) => {
		return ['in', 'up'].includes((currentRoute as TypedRouteFromName<'sign-signType'>).params.signType);
	},
});
```

**Comment by victorgarciaesgi** [comment]
Open a discussion instead of an issue for this

**Comment by szulcus** [comment]
@victorgarciaesgi `currentRoute` have a `TypedRoute` type (unknown), so I think it's a issue but I'll do as you say 🤔

**Comment by victorgarciaesgi** [comment]
It's normal, and with the minimum infos you give I can't understand what you're talking about
