### ISSUE TITLE
Route names of default locale are broken in v3.2.0

### ISSUE THREAD

**Issue by riddla** [victorgarciaesgi/nuxt-typed-router#93]
### before (`v3.1.5`):
```
export type RoutesNamesList =
  | 'agb___en'
  | 'agb___de'
  | 'datenschutz___en'
  | 'datenschutz___de'
  | 'examples-dynamic-fetch___en'
  | 'examples-dynamic-fetch___de'
  | 'examples-dynamic___en'
  | 'examples-dynamic___de'
  | 'examples-dynamic-use-fetch___en'
  | 'examples-dynamic-use-fetch___de'
  | 'examples-i18n-slug___en'
  | 'examples-i18n-static-example___en'
  | 'examples-i18n-slug___de'
  | 'examples-i18n-static-example___de'
  | 'examples___en'
  | 'examples___de'
  | 'examples-page-head-meta___en'
  | 'examples-page-head-meta___de'
  | 'impressum___en'
  | 'impressum___de'
  | 'index___en'
  | 'index___de'
  | 'kontakt___de'
export type WithoutBracket<T extends string> = T extends `:${string}`
  ? never
  : T
```

### after (`v3.2.0`):

```
export type RoutesNamesList =
  | 'agb___en'
  | 'agb'
  | 'datenschutz___en'
  | 'datenschutz'
  | 'examples-dynamic-fetch___en'
  | 'examples-dynamic-fetch'
  | 'examples-dynamic___en'
  | 'examples-dynamic'
  | 'examples-dynamic-use-fetch___en'
  | 'examples-dynamic-use-fetch'
  | 'examples-i18n-slug___en'
  | 'examples-i18n-static-example___en'
  | 'examples-i18n-slug___de'
  | 'examples-i18n-static-example___de'
  | 'examples___en'
  | 'examples'
  | 'examples-page-head-meta___en'
  | 'examples-page-head-meta'
  | 'impressum___en'
  | 'impressum'
  | 'index___en'
  | 'index'
  | 'kontakt'
export type WithoutBracket<T extends string> = T extends `:${string}`
  ? never
  : T
```

When I disable `nuxt-typed-router` completely or use a version prior to `v3.2.0` the routes are back to normal, so I assume something broke in the latest release.

(Nevertheless cheers and many thanks for your very useful package 🙇 👍)

**Comment by victorgarciaesgi** [comment]
Hi! Can you share me your @nuxtjs/i18n config? 
Indeed there where breaking changes in the `3.2.0` that should have fixed the output when using prefixes.
This is normally the correct output, the default locale names are not unprefixed, that way you can still call the route name normally with `useLocalePath`

**Comment by riddla** [comment]
With `v3.2.0` @nuxt/i18n is not able to determine routes for the default locale, e.g. `<nuxt-link :to="localePath({ name: 'agb' })">...</nuxt-link>` returns empty.

My @nuxtjs/i18n config is as follows:

`nuxt.config.ts`
```javascript
  i18n: {
    defaultLocale: 'de',
    // dynamicRouteParams: true,
    locales: [
      {
        code: 'en',
        iso: 'en-US',
      },
      {
        code: 'de',
        iso: 'de-DE',
      },
      {
        code: 'zh',
        iso: 'zh-CN',
      },
    ],
    vueI18n: './i18n.config.ts',
  },
```

`i18n.config.ts`
```javascript
import de from './locales/de.json'
import en from './locales/en.json'

export default {
  legacy: false,
  fallbackLocale: 'de',
  messages: {
    de,
    en,
  },
}
```

**Comment by victorgarciaesgi** [comment]
Thanks for the details, I'll look at it, what Nuxt version are you using?

**Comment by riddla** [comment]
Thank you. We are on `nuxt@3.4.3`.

**Comment by victorgarciaesgi** [comment]
Ok seems like a problem with the `prefix_exept_default` stategy,. With your config and `strategy: prefix` it works

**Comment by victorgarciaesgi** [comment]
@riddla Can you try `3.2.1-beta.0`? Found the problem.
Always hard to work with different strategies, but in a next release I will improve navigation by name with `localePath` the same way I did with paths (Filtering unprefixed named in the arguments)

**Comment by riddla** [comment]
In works (again) in `3.2.1-beta.0` 👍 
Thanks a lot!
